# Generated by Django 6.0 on 2025-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.CharField(help_text='Stable identifier used by plans and frontend.', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('muscle_groups', models.JSONField(blank=True, default=list)),
                ('equipment_required', models.JSONField(blank=True, default=list)),
                ('contraindications', models.JSONField(blank=True, default=list)),
                ('estimated_calories_per_min', models.FloatField(blank=True, null=True)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=16)),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
    ]
